const products = [
  {
    id: 1,
    name: "Almonds",
    nameUrdu: "Badam",
    category: "nuts",
    keywords: ["badam", "almonds", "almond", "badaam", "gilgit", "healthy"],
    pricePerKg: 1500,
    featured: true,
    status: "active",
    image: "images/products/almonds.jpg",
    description: "Premium Skardu almonds, handpicked from mountain orchards."
  },
  {
    id: 2,
    name: "Dried Apricots",
    nameUrdu: "Khubani",
    category: "dried-fruits",
    keywords: ["khubani", "apricot", "dry_fruit", "gilgit"],
    pricePerKg: 2500,
    featured: true,
    status: "active",
    image: "images/products/apricots.jpg",
    description: "Sun-dried Gilgit apricots — naturally sweet, no added sugar."
  },
  {
    id: 3,
    name: "Dried Figs",
    nameUrdu: "Anjeer",
    category: "dried-fruits",
    keywords: ["figs", "dry_figs", "anjeer"],
    pricePerKg: 2300,
    featured: false,
    status: "active",
    image: "images/products/figs.jpg",
    description: "Soft, naturally dried figs from GB orchards."
  },
  {
    id: 4,
    name: "Walnuts",
    nameUrdu: "Akhrot",
    category: "nuts",
    keywords: ["walnuts", "akhrot", "pure"],
    pricePerKg: 3000,
    featured: true,
    status: "active",
    image: "images/products/walnuts.jpg",
    description: "Rich Karakoram walnuts — high omega-3, full flavour."
  },
  {
    id: 5,
    name: "Pine Nuts",
    nameUrdu: "Chilgoza",
    category: "nuts",
    keywords: ["chilgoza", "pine nuts", "pista", "nuts"],
    pricePerKg: 6000,
    featured: true,
    status: "active",
    image: "images/products/pinenuts.jpg",
    description: "Rare Skardu chilgoza — a premium mountain delicacy."
  },
  {
    id: 6,
    name: "Black Mulberry",
    nameUrdu: "Toot Sia",
    category: "dried-fruits",
    keywords: ["toot", "mulberry", "black_mulberry"],
    pricePerKg: 2500,
    featured: false,
    status: "active",
    image: "images/products/blackmulberry.jpg",
    description: "Wild black mulberries, sun-dried in Gilgit valley."
  },
  {
    id: 7,
    name: "White Mulberry",
    nameUrdu: "Toot",
    category: "dried-fruits",
    keywords: ["toot", "white_mulberry", "mulberry"],
    pricePerKg: 3000,
    featured: false,
    status: "active",
    image: "images/products/whitemulberry.jpg",
    description: "Sweet white mulberries, naturally dried at altitude."
  },
  {
    id: 8,
    name: "GB Chocolate (Kilao)",
    nameUrdu: "Kilao",
    category: "specials",
    keywords: ["kilao", "desi_chocolate", "caramel", "nuts"],
    pricePerKg: 6500,
    featured: true,
    status: "active",
    image: "images/products/kilao.jpg",
    description: "Traditional Gilgit desi chocolate — nut caramel, a local treasure."
  },
  {
    id: 9,
    name: "Shilajeet",
    nameUrdu: "Salajeet",
    category: "specials",
    keywords: ["salajeet", "shilajeet", "honey"],
    pricePerKg: 3400,
    unit: "per unit",
    featured: false,
    status: "active",
    image: "images/products/shilajeet.jpg",
    description: "Authentic Karakoram shilajeet — mineral-rich mountain resin."
  },
  {
    id: 10,
    name: "Dried Grapes",
    nameUrdu: "Kishmish",
    category: "dried-fruits",
    keywords: ["kishmish", "dried_grapes", "raisins"],
    pricePerKg: 2500,
    featured: false,
    status: "active",
    image: "images/products/kishmish.jpg",
    description: "Small-batch dried grapes from GB vineyards."
  },
  {
    id: 11,
    name: "Pistachio",
    nameUrdu: "Pista",
    category: "nuts",
    keywords: ["pista", "pistachio", "nuts"],
    pricePerKg: 6000,
    featured: false,
    status: "active",
    image: "images/products/pistachio.jpg",
    description: "Premium quality pistachios, mountain sourced."
  },
  {
    id: 12,
    name: "Gilgit Pure Honey",
    nameUrdu: "Shehed",
    category: "specials",
    keywords: ["honey", "pure_honey", "salajeet"],
    pricePerKg: 1500,
    unit: "per bottle",
    featured: true,
    status: "active",
    image: "images/products/honey.jpg",
    description: "Raw wildflower honey from Gilgit-Baltistan hives."
  }
];